version: 4
updates:
  - package-ecosystem: 'npm'
    directory: '/server'
    schedule:
      interval: 'monthly'

version: 4
updates:
  - package-ecosystem: 'npm'
    directory: '/client'
    schedule:
      interval: 'monthly'
