version: 3
updates:
  - package-ecosystem: "yarn"
    directory: "/server"
    schedule:
      interval: "daily"

version: 3
updates:
  - package-ecosystem: "yarn"
    directory: "/client"
    schedule:
      interval: "daily"
