const {
  REACT_APP_PUBLIC_BACKEND_URL,
  REACT_APP_PUBLIC_MENU,
  REACT_APP_PUBLIC_SEND_MAIL,
  REACT_APP_PUBLIC_LINKEDIN_URL,
  REACT_APP_PUBLIC_GITHUB_URL,
  REACT_APP_PUBLIC_API_KEY,
  REACT_APP_PUBLIC_AUTHORIZATION,
} = process.env;

export const backendURL = REACT_APP_PUBLIC_BACKEND_URL;

export const apiKey = REACT_APP_PUBLIC_API_KEY;

export const authorizationKey = REACT_APP_PUBLIC_AUTHORIZATION;

export const sendMail_api = REACT_APP_PUBLIC_SEND_MAIL;

export const menu_api = REACT_APP_PUBLIC_MENU;

export const linkedinurl = REACT_APP_PUBLIC_LINKEDIN_URL;

export const githubURL = REACT_APP_PUBLIC_GITHUB_URL;
